# run with "tomlrun <script>" or "npm run tomlrun <script>"

fmt = """\
  prettier \
    --ignore-path="./.gitignore" -w \
    **.scss **.ts **.tsx **.js **.jsx **.css \
  && cd mnote-app/src-tauri && cargo fmt
  """

# pass arguments to prettier instead of running it on the whole project
prettier = 'prettier --ignore-path="./.gitingore" -w' # <glob...>

lint = """eslint \
  --ignore-path .gitignore \
  **/**.ts **/**.tsx **/**.js **/**.jsx \
  """

lint-rs = "cd mnote-app/src-tauri && cargo clippy && cargo check"

# same as the prettier script
eslint = "eslint --ignore-path .gitignore"

# run mnote-app commands from here
app = "cd mnote-app && npm run" # <script name>

# for gitpod workspaces
gitpod = """
  cd ..

  # install deno (as the linter)
  curl -fsSL https://deno.land/x/install/install.sh | sh
  export DENO_INSTALL="/home/gitpod/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"

  # install dependencies
  cd mnote
  npm i -g npm@8
  npm --version
  npm i
  git reset --hard
  """
