name: "build-release"
on: [workflow_dispatch]

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
  
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: install dependencies
      shell: pwsh
      run: .\install.ps1

    - name: bundle
      run: cd mnote-app && npm run xbuild

    - name: build release
      run: cd mnote-app && npm run tauri build

    - name: upload (windows)
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}
        path: ./mnote-app/src-tauri/target/debug/bundle

    - name: upload (macos)
      if: matrix.platform == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}
        path: ./mnote-app/src-tauri/target/debug/bundle
